name: ayurvedic
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_easyloading: ^3.0.5
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  get_storage: ^2.1.1
  http: ^1.5.0
  intl: ^0.20.2
  numberpicker: ^2.1.2
  page_transition: ^2.2.1
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.2.3
  build_runner: ^2.8.0

flutter:
  uses-material-design: true

  assets: 
    - assets/images/ 

  fonts: 
    - family: Poppins 
      fonts:
        - asset:  assets/fonts/Poppins-Regular.ttf
        - asset:  assets/fonts/Poppins-Medium.ttf
          weight: 500
    
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Light.ttf
